/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004e5c",
        "on-tertiary-container": "#7e000f",
        "tertiary-fixed": "#ffdad7",
        "background": "#111316",
        "on-primary-container": "#00424f",
        "surface-dim": "#111316",
        "primary-container": "#06b6d4",
        "secondary-container": "#ee9800",
        "tertiary-container": "#ff817a",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        "surface-variant": "#333538",
        "on-error-container": "#ffdad6",
        "surface-bright": "#37393d",
        "secondary-fixed": "#ffddb8",
        "on-tertiary": "#68000a",
        "surface-container-low": "#1a1c1f",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ffb95f",
        "primary-fixed-dim": "#4cd7f6",
        "on-secondary": "#472a00",
        "on-secondary-container": "#5b3800",
        "on-primary": "#003640",
        "outline-variant": "#3d494c",
        "primary": "#4cd7f6",
        "on-primary-fixed": "#001f26",
        "outline": "#869397",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#653e00",
        "secondary": "#ffb95f",
        "on-surface": "#e2e2e6",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface": "#111316",
        "error": "#ffb4ab",
        "inverse-primary": "#00687a",
        "surface-container-high": "#282a2d",
        "on-secondary-fixed": "#2a1700",
        "surface-container-highest": "#333538",
        "surface-tint": "#4cd7f6",
        "inverse-on-surface": "#2f3034",
        "on-surface-variant": "#bcc9cd",
        "tertiary": "#ffb3ad",
        "primary-fixed": "#acedff",
        "on-background": "#e2e2e6",
        "surface-container-lowest": "#0c0e11",
        "surface-container": "#1e2023",
        "inverse-surface": "#e2e2e6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "240px",
        "gutter": "24px",
        "topbar-height": "64px",
        "margin-page": "32px",
        "stack-sm": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-default": ["Geist Sans", "sans-serif"],
        "body-sm": ["Geist Sans", "sans-serif"],
        "headline-lg": ["Geist Sans", "sans-serif"],
        "headline-md": ["Geist Sans", "sans-serif"],
        "label-caps": ["Geist Sans", "sans-serif"],
        "technical-data": ["Geist Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
